#Mit input() wird der Wert der Variablen der Wert aus der Konsole zugewiesen
##print("----------------------")
##print("")
##name=input("Name Bitte")
##print("Name:", name)
##print("")
##alter=input("Alter Bitte")
##print("Alter:", alter )
##print("")
##wohnort=input("Wohnort (mit adresse un PLZ)")
##print("Wohnort:", wohnort)
##print("----------------------")
#1) Print(3+3) 
#2) print("3+3") 
#3) print("6+1/2=", 6+1/2 ) 
#4) print(Aloha) 
#4) print("Aloh", 'a', "a")
#Datentyp Float -> beschreibt Fließkommazahlen.
#Das "Komma" ist ein Python Punkt (6,5 -> 6.5)